menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/lili21

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: lili21githubio

# Analytics
# google-analytics:
ga: UA-81262565-1

# Copyright Infomation
startyear: 2016
